<!DOCTYPE html>
<html lang="th">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BUNNY WORKS</title>
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap" rel="stylesheet">
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: 'Orbitron', sans-serif;
            color: #b3b3b3;
            background: #121212;
            overflow-x: hidden;
        }

        header {
            background-color: #1e1e1e;
            border-bottom: 2px solid #00b3e6;
            padding: 15px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.5);
        }

        .logo {
            display: flex;
            align-items: center;
            font-size: 1.5em;
            color: #00b3e6;
        }

        .logo img {
            height: 50px;
            margin-right: 10px;
        }

        nav {
            display: flex;
            gap: 20px;
        }

        nav a {
            color: #b3b3b3;
            text-decoration: none;
            font-size: 1em;
            padding: 10px 15px;
            border-radius: 30px;
            background: rgba(0, 179, 230, 0.2);
            transition: background-color 0.3s, color 0.3s;
        }

        nav a:hover {
            background-color: #00b3e6;
            color: #121212;
        }

        .hero {
            height: 80vh;
            background: url('https://example.com/sci-fi-background.png') no-repeat center center;
            background-size: cover;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            padding: 40px;
            color: #00b3e6;
        }

        .hero h1 {
            font-size: 3em;
            margin: 0;
        }

        .hero p {
            font-size: 1.2em;
            margin: 20px 0;
        }

        .hero button {
            background: linear-gradient(to top, #00b3e6, #000);
            border: none;
            color: #fff;
            padding: 15px 25px;
            font-size: 18px;
            cursor: pointer;
            border-radius: 30px;
            transition: background 0.3s, transform 0.3s, box-shadow 0.3s;
        }

        .hero button:hover {
            background: linear-gradient(to top, #000, #00b3e6);
            transform: scale(1.05);
            box-shadow: 0 0 15px rgba(0, 179, 230, 0.7);
        }

        .hero img {
            width: 150px;
            height: auto;
            margin-top: 20px;
        }

        .services {
            padding: 50px 20px;
            background-color: #1e1e1e;
            border-top: 2px solid #00b3e6;
            text-align: center;
        }

        .services h2 {
            font-size: 2.5em;
            color: #00b3e6;
        }

        .service-item {
            background: rgba(0, 179, 230, 0.1);
            border-radius: 15px;
            padding: 20px;
            margin: 20px;
            width: calc(33.333% - 40px);
            display: inline-block;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);
            color: #b3b3b3;
            transition: transform 0.3s;
        }

        .service-item:hover {
            transform: scale(1.05);
        }

        .service-item h3 {
            color: #00b3e6;
        }

        .service-item p {
            font-size: 1em;
        }

        .portfolio {
            padding: 50px 20px;
            background-color: #1e1e1e;
            border-top: 2px solid #00b3e6;
            text-align: center;
        }

        .portfolio img {
            max-width: 100%;
            border-radius: 15px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);
        }

        footer {
            background-color: #1e1e1e;
            color: #b3b3b3;
            text-align: center;
            padding: 20px;
            border-top: 2px solid #00b3e6;
        }

        @media (max-width: 768px) {
            .service-item {
                width: calc(50% - 40px);
            }
        }

        @media (max-width: 480px) {
            .service-item {
                width: 100%;
            }
        }
    </style>
</head>
<body>
    <header>
        <div class="logo">
            <img src="assets/logo-removebg-preview.png" alt="Bunny Logo">
            <span>BUNNY WORKS</span>
        </div>
        <nav>
            <a href="#">Home</a>
            <a href="#">Services</a>
            <a href="#">Portfolio</a>
            <a href="#">Contact</a>
        </nav>
    </header>

    <section class="hero">
        <h1>Welcome to BUNNY WORKS</h1>
        <p>Your creative solution for modern and playful web design.</p>
        <button>Get Started</button>
        <img src="assets/bunny-unscreen.gif" alt="Cute Bunny">
    </section>

    <section class="services">
        <h2>Our Services</h2>
        <div class="service-item">
            <h3>Web Design</h3>
            <p>Design engaging and visually appealing websites.</p>
        </div>
        <div class="service-item">
            <h3>SEO Optimization</h3>
            <p>Enhance your website's search engine ranking.</p>
        </div>
        <div class="service-item">
            <h3>Mobile App Development</h3>
            <p>Create user-friendly mobile applications.</p>
        </div>
    </section>

    <section class="portfolio">
        <h2>Our Work</h2>
        <img src="https://example.com/portfolio.jpg" alt="Portfolio Example">
    </section>

    <footer>
        <p>&copy; 2024 BUNNY WORKS. All rights reserved.</p>
    </footer>
</body>
</html>
